### ISSUE TITLE
Brightness does not update on startup

### ISSUE THREAD

**Issue by nanthony21** [saalfeldlab/bigwarp#135]
I am running Big Warp from a script like this:

```
    a0 = ij.convert().convert(movingDataSet, ipClass)
    a1 = ij.convert().convert(targetDataSet, ipClass)
    bwData = BigWarpInit.initData()
    BigWarpInit.add(bwData, a0, 0, 0, True)
    BigWarpInit.add(bwData, a1, 1, 0, False)
    bwData.wrapUp()

    BW = new BigWarp(bwData, "Big Warp", new ProgressWriterIJ())
```

`dataSet1` is an 8-bit image and `dataSet2` is a floating point image from 0-1. However, when the displays open up they are shown as completely black. If I go to the "Brightness & Color" dialog I see that the settings for `dataSet1` have already been set to 0-255 but that the display just hasn't updated. For `dataSet2` it is set from 0-65535 even though the data only goes up to 1.0

**Comment by bogovicj** [comment]
@nanthony21 

couple follow up questions:

Are you using the most recent bigwarp?  this was an issue i fixed in https://github.com/saalfeldlab/bigwarp/commit/7677a2b94605226edca7c27a668143787d222f4a , but since youre calling bigwarp yourself, and from python i could imagine the behavior is different.

what kinds of objects are `movingDataSet` and `targetDataSet` ?

One workaround could beAre you using the most recent bigwarp?  this was an issue i fixed in https://github.com/saalfeldlab/bigwarp/commit/7677a2b94605226edca7c27a668143787d222f4a , but since youre calling bigwarp yourself, and from python i could imagine the behavior is different.

I could show you how to set the display ranges, would that suffice as a workaround while I investigate further?

**Comment by nanthony21** [comment]
Thanks @bogovicj ,

I couldn't figure out how to check the version so I'm not sure what I was using. However, I changed the version in my pyimagej initialization like so:

`ij = imagej.init(['net.imagej:imagej', 'net.imagej:imagej-legacy', 'sc.fiji:fiji', 'sc.fiji:bigwarp_fiji:7.0.4'], headless=False)`

and now the images initialize correctly. One very minor issue I still see is that the "Brightness  & Color" channel for the 0-1 floating point image still shows a range of 0-65535 even though the image is actually displaying 0.0-1.0 . This doesn't matter for my usage though.

Thanks, for the help!
